modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
displayName = "${display_name}"
modId = "${mod_id}"
description = '''${description}'''
version = "${version}"
authors = "${authors}"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
